services:
  qdrant:
    image: qdrant/qdrant:v1.16.3
    container_name: agent_qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    volumes:
      - qdrant:/qdrant/storage
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "exec 3<>/dev/tcp/127.0.0.1/6333 && echo -e 'GET /readyz HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && grep -q 'HTTP/1.1 200' <&3",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - agent-shared-network
  mongo:
    image: mongo:8.2.6-rc0
    container_name: agent_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')",
          "--username",
          "${MONGO_USERNAME}",
          "--password",
          "${MONGO_PASSWORD}",
          "--authenticationDatabase",
          "admin",
        ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 15s
    networks:
      - agent-shared-network
  redis:
    image: redis:8.2.3
    container_name: agent_redis
    restart: always
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASS}",
        "--maxmemory",
        "50mb",
        "--maxmemory-policy",
        "volatile-ttl",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/redis/storage
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - agent-shared-network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent_server
    restart: always
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", ""]
      interval: 10s
      timeout: 5s
      retries: 4
    networks:
      - agent-shared-network
networks:
  agent-shared-network:
    external: true

volumes:
  qdrant:
  mongodb-data:
  redis-data:
