services:
  searxng:
    image: searxng/searxng:2026.3.12-3d3a78f3a
    container_name: agent_searxng
    restart: always
    ports:
      - "9090:8080"
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
    volumes:
      - ./searxng:/etc/searxng
  qdrant:
    image: qdrant/qdrant:v1.16.3
    container_name: agent_qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant:/qdrant/storage
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "exec 3<>/dev/tcp/127.0.0.1/6333 && echo -e 'GET /readyz HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && grep -q 'HTTP/1.1 200' <&3",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - agent-shared-network
  mongo:
    image: mongo:8.2.6-rc0
    container_name: agent_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')",
          "--username",
          "${MONGO_USERNAME}",
          "--password",
          "${MONGO_PASSWORD}",
          "--authenticationDatabase",
          "admin",
        ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 15s
    networks:
      - agent-shared-network
  redis:
    image: redis:8.2.3
    container_name: agent_redis
    restart: always
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASS}",
        "--maxmemory",
        "50mb",
        "--maxmemory-policy",
        "volatile-ttl",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/redis/storage
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - agent-shared-network
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: agent_server
    restart: no
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 4
    networks:
      - agent-shared-network
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: agent_app
    restart: always
    ports:
      - "8501:8501"
    # depends_on:
    #   server:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 4
    networks:
      - agent-shared-network
networks:
  agent-shared-network:
    external: true

volumes:
  qdrant:
  mongodb-data:
  redis-data:
