[theme]
base = "dark"

[server]
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "none"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
